print(5*'-=-')
valor = input('Digite algo sem espaços: ')
print()
print(type(valor))
print(f'É alfanumerico? {valor.isalnum()}')
print(f'É alfabetico? {valor.isalpha()}')
print(f'É minusculo? {valor.islower()}')
print(f'É maiusculo? {valor.isupper()}')
print(f'É numerico? {valor.isnumeric()}')